### ISSUE TITLE
mr anushi am haves issue with my zycoball phone please help :(((((((((((((((

### ISSUE THREAD

**Issue by weyesnob** [weyesnocommit/metadata-data-basedata-truedata#1] opened 2022-04-24 12:48 UTC
when i it on turn it show on display am but latter off turns and am notw know 

m
m
supper disappoint mr anushi o
![20210207_211407](https://user-images.githubusercontent.com/104307527/164977265-56db9033-11a7-4320-b252-a49e309066ff.png)
k

**Comment by weyesnocommit** [comment] 2022-04-24 12:58
Make you try something or through it out

**Comment by weyesnob** [comment] 2022-04-24 13:03
Deep thank infact this solfe my problam dot

**Comment by weyesnocommit** [comment] 2022-04-24 13:07
shit broo actually our government dont welcome close door hence we reopen d issue

**Comment by weyesnob** [comment] 2022-04-24 13:54
what are you doing in my email .

**Comment by weyesnocommit** [comment] 2022-05-08 21:30
mr anushi am most to email to email so we can business on the business. i hate talk talk hence am chup chup

**Comment by weyesnob** [comment] 2022-05-08 23:51
i WON this email. Why are you in it

**Comment by weyesnocommit** [comment] 2022-05-12 15:52
infact am you access token steal mr anushi

**Comment by weyesnocommit** [comment] 2022-05-12 15:53
- [ ] Mubaraq
- [X] Cool

**Comment by weyesnocommit** [comment] 2022-05-12 15:53
### Good

**Comment by weyesnocommit** [comment] 2022-05-12 15:54
@weyesnob you snob 

- [X] We yes
- [ ] Snob business

**Comment by weyesnob** [comment] 2022-05-13 19:21
D problam was solfe by through out all other number from my phone

**Comment by weyesnocommit** [comment] 2022-05-14 18:35
mr anushi d issue is not solfe and d zycoball phone is brick. Why most you lie it

**Comment by weyesnob** [comment] 2022-05-15 11:37
weyesno take responsibility for bricked phone dot thanks dot

**Comment by weyesnob** [comment] 2022-05-20 15:59
WHY NBODYO REPLY MY PROBLAM

**Comment by weyesnocommit** [comment] 2022-05-29 15:08
[d](url)

**Comment by weyesnocommit** [comment] 2022-05-29 15:08
duplicate of issue [numbers ones](https://github.com/weyesnocommit/metadata-data-basedata-truedata/issues/1)

**Closed as completed by weyesnocommit** 2022-05-29 15:08 UTC
